Various fixes
openturns/openturns pull request #1565
Opened 2020-08-04 07:16 UTC by jschueller

- #1564

2020-08-04 08:32 UTC, jschueller commented
@regislebrun I plan to add more fixes as they come, that's why this PR is marked "draft" (you can see the color: it's gray), when it's ready to review I'll mark it as "ready" (it goes green)

2020-08-06 19:32 UTC, josephmure commented
@jschueller  I am currently rewriting the `SobolIndicesExperiment` doc page as part of #1562. Could you please delete commit 64514f6 so as to avoid merge conflicts?

2020-08-07 06:28 UTC, jschueller commented
> @jschueller I am currently rewriting the `SobolIndicesExperiment` doc page as part of #1562. Could you please delete commit [64514f6](https://github.com/openturns/openturns/commit/64514f675bc555c0212551e58c2a04f02562405e) so as to avoid merge conflicts? The rewrite is going to fix #1567 anyway.

ok

2020-08-21 08:16 UTC, jschueller commented
This is ready to go

2020-08-24 14:16 UTC, josephmure requested changes
My main comment concerns the new calibration example with no inputs: could you please produce it as a Python file in order to fit #1574, using [this](https://github.com/openturns/openturns/blob/0224e7b581878431e52e5af357def2fbdbc5d9b4/python/doc/examples/py_calibration/bayesian_calibration/plot_bayesian_calibration.py) as a template?

2020-08-24 14:16 UTC, josephmure commented on python/doc/examples/calibration/calibration_withoutobservedinputs.ipynb
> +{
Could you please convert this example to a Python script with RST commands that could work with #1574? You can use [this file](https://github.com/openturns/openturns/blob/0224e7b581878431e52e5af357def2fbdbc5d9b4/python/doc/examples/py_calibration/bayesian_calibration/plot_bayesian_calibration.py) as template.

2020-08-24 14:16 UTC, josephmure commented on python/src/LinearBasisFactory_doc.i.in
> +[1,2,3]"
Wouldn't it be better to print the basis? Isn't there a pretty print that could be used?

2020-08-24 14:16 UTC, josephmure commented on python/src/LinearModelAlgorithm_doc.i.in
> +if basis is orthogonal) and large dataset.
```suggestion
if the basis is orthogonal) and large dataset.
```

2020-08-24 14:16 UTC, josephmure commented on python/src/LinearModelAlgorithm_doc.i.in
> +Default method is `QR`. User might choose also `SVD` or `Cholesky` (useful
```suggestion
Default method is `QR`. User might also choose `SVD` or `Cholesky` (useful
```
Seems more natural to me.

2020-08-24 14:16 UTC, josephmure commented on python/src/LinearModelAlgorithm_doc.i.in
>  help the diagnostic of the linearity."
> The evaluation of the coefficients is completed by some useful parameters that could
help the diagnostic of the linearity.

It is good that you corrected the typo, but I don't understand what this sentence means.

2020-08-24 14:16 UTC, josephmure commented on python/src/QuadraticBasisFactory_doc.i.in
> +>>> f = ot.AggregatedFunction(basis)
Same as before: wouldn't it be better to simply print the basis?

2020-08-24 14:16 UTC, josephmure commented on python/src/ConstantBasisFactory_doc.i.in
> +>>> f = ot.AggregatedFunction(basis)
Wouldn't it be better to simply print the basis?

2020-08-24 14:16 UTC, josephmure commented on python/src/SobolIndicesAlgorithmImplementation_doc.i.in
> +    S_i & = & \frac{V_i}{\Var{Y}} \\
Great that you included this correction!

2020-08-31 13:26 UTC, sofianehaddad approved these changes

2020-09-07 09:58 UTC, merged