Fixes typos
openturns/openturns pull request #1965
Opened 2022-02-16 13:10 UTC by vchabri

2022-02-17 21:17 UTC, josephmure requested changes

2022-02-17 21:17 UTC, josephmure commented on python/doc/examples/meta_modeling/general_purpose_metamodels/plot_taylor_approximation.py
> +# Plot 2nd output of our model with x1=x0_1.
```suggestion
# Plot the second output of our model with :math:`x_1=x_{0,1}`.
```
To keep notations consistent with the first equation.

2022-02-17 21:17 UTC, josephmure commented on python/doc/examples/meta_modeling/general_purpose_metamodels/plot_taylor_approximation.py
> +# Plot second output of our model with x1=x0_1.
```suggestion
# Plot the second output of our model with :math:`x_1=x_{0,1}`.
```
Same.

2022-02-17 21:18 UTC, josephmure commented
This goes beyond what @mbaudin47 requested in #1935. Good job!

2022-02-18 07:53 UTC, merged

2022-02-18 08:03 UTC, josephmure commented
I guess another PR will be required to fix those additional typos.

2022-02-18 08:09 UTC, jschueller commented
Yes, sorry

2022-02-19 19:04 UTC, mbaudin47 commented
It seems that the backslashes were not taken into account:

![image](https://user-images.githubusercontent.com/31351465/154815213-f6b87b21-c196-44b1-af04-8c5cee2360c6.png)

2022-02-19 20:25 UTC, josephmure commented
@mbaudin47 CircleCI failed to publish the doc when #1977 was merged, otherwise we would see that all changes were taken into account:

https://8612-40717169-gh.circle-artifacts.com/0/html/auto_meta_modeling/general_purpose_metamodels/plot_taylor_approximation.html#sphx-glr-auto-meta-modeling-general-purpose-metamodels-plot-taylor-approximation-py

2022-02-23 22:26 UTC, mbaudin47 commented
Ok.