Fixes typos cross_validation.rst
openturns/openturns pull request #1969
Opened 2022-02-16 13:21 UTC by efekhari27

2022-02-17 20:46 UTC, josephmure requested changes

2022-02-17 20:46 UTC, josephmure commented on python/doc/theory/meta_modeling/cross_validation.rst
>    :math:`\underline{\underline{\Psi}} (\underline{\underline{\Psi}}^{\textsf{T}}\underline{\underline{\Psi}})^{-1} \underline{\underline{\Psi}}^{\textsf{T}}`
```suggestion
:math:`\underline{\underline{\Psi}} (\underline{\underline{\Psi}}^{\textsf{T}}\underline{\underline{\Psi}})^{-1} \underline{\underline{\Psi}}^{\textsf{T}}`
```
Maybe unindenting this line will make the build work.

2022-03-28 13:43 UTC, josephmure approved these changes
Good job.

2022-03-28 15:46 UTC, jschueller commented
Do you know where the typos are ? The indentation changes are hiding the corrections.

2022-03-28 20:17 UTC, josephmure commented
I am not sure any actual "typo" was corrected. The issue that this PR corrects is the faulty indentation, which resulted in a huge blank space at the top of the page: see the first point in issue #1935. IMO the PR fulfills its purpose and can be merged. You can change the commit message when you merge if you find it inappropriate.

2022-03-29 06:33 UTC, merged

2022-03-29 06:33 UTC, jschueller commented
its fine then