Fixed PCE example for CleaningStrategy
openturns/openturns pull request #2001
Opened 2022-03-28 12:40 UTC by mbaudin47

This PR fixes several issues in the example [Create a sparse chaos by integration](https://openturns.github.io/openturns/master/auto_meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.html).
- Removes a large blank space in the begining.
- Fixes the equation defining the multiindex set for significant coefficients.
- Removes the approximately equal mathematical sign and replace it by an equality.
- Fixes the analysis of the selection of the coefficients and makes clear that the first coefficient a0 is always selected.
- Formats the name of the class.

2022-03-29 14:28 UTC, jschueller approved these changes

2022-03-31 11:57 UTC, josephmure requested changes
The example is much tidier now! A few typos still remain.

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# and maximum rank :math:`j \in \mathbb{N}` is ([blatman2009]_ page 74) is :
```suggestion
# and maximum rank :math:`j \in \mathbb{N}` is ([blatman2009]_ page 74):
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# The rank is now an hyperparameter of the model: [blatman2009]_ suggests
```suggestion
# The rank is now a hyperparameter of the model: [blatman2009]_ suggests  
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# The `CleaningStrategy` uses the following criteria to select the coefficients :
```suggestion
# The :class:`~openturns.CleaningStrategy` uses the following criteria to select the coefficients :
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# where :math:`\epsilon` is the significance factor, default is
```suggestion
# where :math:`\epsilon` is the significance factor, which by default is 
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
>  def printCoefficientsTable(
In the docstring of `printCoefficientsTable`, there is a type: "stricly" instead of "strictly", but I cannot reach it with a GitHib suggestion.

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# is performed by the `MetaModelValidation` class.
```suggestion
# is performed by the :class:`~openturns.MetaModelValidation` class.
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# The following function creates a validation plot using the `draw` method
```suggestion
# The following function creates a validation plot using the
# :meth:`~openturns.MetaModelValidation.drawValidation` method  
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# We consider the Ishigami model which has three inputs uniform in the
```suggestion
# We consider the Ishigami model.
# Its three inputs are i.i.d. random variables that follow the uniform distribution on the
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# produce Legendre polynomials.
```suggestion
# marginals are uniform, the :class:`~openturns.OrthogonalProductPolynomialFactory` class
# produces Legendre polynomials.
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# number depending on the total degree. The `getMaximumDegreeStrataIndex` method
```suggestion
# number depending on the total degree.
# The :meth:`~openturns.EnumerateFunction.getMaximumDegreeStrataIndex` method
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# with the `getStrataCumulatedCardinal` method.
```suggestion
# with the :meth:`~openturns.EnumerateFunction.getStrataCumulatedCardinal` method.
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# `GaussProductExperiment` class to create the quadrature, using 6 nodes on each
```suggestion
# :class:`~openturns.GaussProductExperiment` class to create the quadrature,
# using 6 nodes on each
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# these coefficient have a very high polynomial degree. Indeed, it occurs that
```suggestion
# these coefficients have a very high polynomial degree. Indeed, it occurs that   
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# criteria selects them as significant coefficients, which leads to a poor metamodel
```suggestion
# criteria selects them as significant coefficients, which leads to a poor metamodel.
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# degree equal as large as 7.
```suggestion
# degree as large as 7.
```

2022-03-31 11:57 UTC, josephmure commented on python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cleaning_strategy.py
> +# printed in the Terminal (but not in the Jupyter output). For each step of
Does it make sense to talk about the Jupyter output in a Python script? BTW, is that still true?

2022-05-04 14:51 UTC, jschueller commented
good to go @josephmure ?

2022-05-04 17:17 UTC, merged