Enhance EllipticalDistribution
openturns/openturns pull request #2196
Opened 2022-11-29 12:11 UTC by jschueller

- Matrix: Add computeRegularizedCholesky

2022-12-07 16:17 UTC, jschueller commented on lib/src/Base/Type/MatrixImplementation.cxx
> +      if (maxEV < 0.0)
it would fail before that in computeLargestEigenValueModule, lets add checks there

2022-12-07 16:49 UTC, josephmure commented on lib/src/Base/Type/MatrixImplementation.cxx
> +      if (maxEV < 0.0)
Good idea! Thanks.

2022-12-08 13:48 UTC, jschueller commented on lib/src/Uncertainty/Model/EllipticalDistribution.cxx
> +        inverseR_(i, j) = inverseShape(i, j) * sigmaIJ;
I guess not, for the gradient because we still have to multiply by sigma

2022-12-09 09:47 UTC, josephmure approved these changes

2022-12-10 22:25 UTC, regislebrun commented
I don't understand the need to keep so many matrices (4) when either the Cholesky factor of the correlation (or its inverse) would allow to compute everything with essentially no speed penalty. I am not sure that a cache mechanism is worth the effort for the other matrices. Do you have an actual use-case showing this need?
For me it is a first step toward a really lean EllipticalDistribution class, allowing to e.g. associate such a distribution to a GaussianProcess with no significant memory footprint.

2022-12-12 15:59 UTC, jschueller commented
I was assuming these were more likely here for performance reasons, but sure, we can uncache the inverseR_ and compute inverseCholesky_ from cholesky_ so as to store only 2/5 matrix:

before:
```
  /** The correlation matrix (Rij) of the distribution */
  mutable CorrelationMatrix R_;

  /** The shape matrix of the distribution = Diag(sigma_) * R_ * Diag(sigma_) */
  mutable CovarianceMatrix shape_;

  /** The inverse of the correlation matrix of the distribution */
  SymmetricMatrix inverseR_;

  /** The Cholesky factor of the shape matrix shape_ = cholesky_ * cholesky_.transpose() */
  TriangularMatrix cholesky_;

  /** The inverse Cholesky factor of the covariance matrix */
  TriangularMatrix inverseCholesky_;
```

after:
```
  /** The correlation matrix (Rij) of the distribution */
  mutable CorrelationMatrix R_;

  /** The Cholesky factor of the shape matrix shape_ = cholesky_ * cholesky_.transpose() */
  mutable TriangularMatrix cholesky_;
```

2022-12-12 16:21 UTC, jschueller commented
CI fails because of #2204, @regislebrun can we merge #2187 ?

2023-01-17 14:03 UTC, jschueller commented
@regislebrun I've reworked this branch, now where we needed cholesky_ we solve a linear system with inverseCholesky_ instead of rebuilding the whole cholesky factor. This time we prefer to drop cholesky_ instead of inverseCholesky_ to favor computePDF for likelihood computations (& computeLogPDF), instead of inverseCholesky_ for getRealization.

Because we want to avoid extra copies for TriangularMatrix in mutable attributes for non-const solveLinearSystemmethods, we need to split solveLinearSystem(bool keepIntact) into two methods: solveLinearSystemInPlace, solveLinearSystem() const, so there are several commits to do that for all solveLinearSystem methods, but we should avoid that design.

2023-01-18 10:38 UTC, josephmure requested changes

2023-01-18 10:38 UTC, josephmure commented on python/test/t_Normal_std.py
> -assert dist.getCorrelation()[0, 0] > 1.0, "not regularized"
Why remove this test?

2023-01-18 10:39 UTC, jschueller commented on ChangeLog
> + * Deprecated EllipticalDistribution::getInverseCorrelation
I dont think it will ever be useful, and its not even used internally

2023-01-18 10:40 UTC, jschueller commented on python/test/t_Normal_std.py
> -assert dist.getCorrelation()[0, 0] > 1.0, "not regularized"
now getCorrelation is 1.0 there

2023-01-18 13:17 UTC, josephmure commented on python/test/t_Normal_std.py
> -assert dist.getCorrelation()[0, 0] > 1.0, "not regularized"
OK

2023-02-14 12:00 UTC, regislebrun commented
@jschueller Ok you are right, the side effect of removing the correlation matrix is significant and can be postponed to another PR. Is this PR ready for a review or do you plan to add significant changes?

2023-02-14 12:19 UTC, jschueller commented
no its ready, I just had to rebase to master

2023-02-23 05:57 UTC, josephmure approved these changes

2023-03-16 08:59 UTC, regislebrun approved these changes

2023-03-16 08:59 UTC, merged