Added SpecFunc::AccurateSum
openturns/openturns pull request #2203
Opened 2022-12-08 08:36 UTC by regislebrun

This method allows to compute the sum of a sequence of floats with an extended precision, using either MPFR or Kahan's method.

2022-12-08 08:38 UTC, jschueller commented on lib/src/Uncertainty/Model/DistributionImplementation.cxx
> +    std::cerr << "probabilities=" << probabilities << std::endl;
leftover from debug?

2022-12-08 20:08 UTC, josephmure requested changes

2022-12-08 20:08 UTC, josephmure commented on python/test/t_SpecFunc_std.py
> +print("accurate sum(x)=", ot.SpecFunc.AccurateSum(x))
```suggestion
assert sum(x) == 0.0, "sum(x) nonzero"
assert ot.SpecFunc.AccurateSum(x) == 1.0, "accurate sum(x) not 1"
```

2022-12-08 20:08 UTC, josephmure commented on python/test/t_SpecFunc_std.expout
> +accurate sum(x)= 1.0
```suggestion
```

2022-12-08 20:23 UTC, regislebrun commented on lib/src/Uncertainty/Model/DistributionImplementation.cxx
> +    std::cerr << "probabilities=" << probabilities << std::endl;
Yep. Fixed.

2022-12-08 20:25 UTC, regislebrun commented on lib/src/Uncertainty/Algorithm/Analytical/SystemFORM.cxx
> +    LOGINFO(OSS() << "SystemFORM: poincarre probability [" << k << "]=" << signedProbabilities[k]);
@josephmure This one is from @jschueller and is fixed in another PR

2022-12-08 22:29 UTC, josephmure approved these changes

2022-12-09 07:41 UTC, jschueller approved these changes

2022-12-12 16:51 UTC, jschueller commented
you can fix the conflicts now

2022-12-14 13:03 UTC, jschueller commented
the $ms compiler is not happy :[

2022-12-14 13:43 UTC, regislebrun commented
@jschueller I saw it. It must be linked with a stupid optimization simplifying Kahan's algorithm as if float arithmetic was associative and commutative. Maybe a pragma such as
```
#pragma optimize( "", off )
```
would do the job ([details](https://learn.microsoft.com/en-us/cpp/preprocessor/optimize?view=msvc-170)), as suggested [here](https://stackoverflow.com/questions/32718989/disable-optimization-on-specific-msvc-version)

2022-12-16 08:22 UTC, regislebrun commented
@jschueller After inspection, it is not the fault of the MS compiler, the test was too stringent for Kahan's method. It was masked on Linux platform due to the use of the alternative MPFR implementation. Any hope to have it on Windows?

2022-12-16 09:53 UTC, josephmure commented
@regislebrun If the test is too stringent, it should be relaxed IMO. Its purpose is to test that Kahan's method is well implemented so it should account for possible platform-related differences.

2022-12-16 17:14 UTC, regislebrun commented
@josephmure You are right, and it is exactly what it does now. The Kahan method gives the exact same results on all the platforms and hopefully will continue to give the same results in the future ;-)

2022-12-16 20:26 UTC, jschueller commented
on windows we distribute mingw binaries and mpfr is available there, so I'll probably wont bother testing mpfr with msvc

2022-12-17 08:43 UTC, jschueller commented on lib/src/Base/Func/SpecFunc/SpecFunc.cxx
> +#pragma optimize( "", off )
so optimization can be re-enabled now ?
note that _MSC_VER implies _WIN32

2022-12-17 16:11 UTC, jschueller approved these changes

2023-01-13 15:37 UTC, jschueller commented on lib/src/Base/Func/SpecFunc/SpecFunc.cxx
> +// To prevent Microsoft compiler for abusive optimization
drop this one

2023-01-13 21:00 UTC, regislebrun commented on lib/src/Base/Func/SpecFunc/SpecFunc.cxx
> +// To prevent Microsoft compiler for abusive optimization
done

2023-01-24 08:49 UTC, merged