Misc
openturns/openturns pull request #2246
Opened 2023-02-24 17:18 UTC by jschueller

- Fix arnings from gcc13

2023-03-16 11:03 UTC, mbaudin47 requested changes

2023-03-23 09:10 UTC, sofianehaddad approved these changes

2023-03-23 09:12 UTC, sofianehaddad commented
Nice catch in `Kriging` thanks

2023-04-11 17:27 UTC, mbaudin47 commented on python/src/SpecFunc_doc.i.in
> +    Whether to return 1-p or not.
```suggestion
    If False, then return min(1, max(0,p)). Otherwise return 1 - min(1, max(0,p)). 
```

2023-04-12 06:20 UTC, jschueller commented
I put the image in the description
the circleci redirector stuff is broken atm

2023-04-12 08:10 UTC, regislebrun approved these changes

2023-04-12 08:16 UTC, merged

2023-04-12 17:56 UTC, mbaudin47 commented
I asked for a change:

![image](https://user-images.githubusercontent.com/31351465/231542075-fbdcb865-747a-4446-91fe-660b482298c4.png)

and was clear about it:

![image](https://user-images.githubusercontent.com/31351465/231542225-dcc9095f-9f87-41cc-bfef-f1ccbead5f13.png)

so i guess that you forgot about it. Can you please revert that merge?

2023-04-13 06:26 UTC, jschueller commented
too late to revert, I guess we can do that in another branch