Update KarhunenLoeveValidation_doc.i.in
openturns/openturns pull request #2381
Opened 2023-09-06 09:38 UTC by adutfoy

Changed the doc of the computeResidual() method

2023-09-07 06:50 UTC, jschueller approved these changes

2023-09-09 15:03 UTC, mbaudin47 requested changes

2023-09-09 15:03 UTC, mbaudin47 commented on python/src/KarhunenLoeveValidation_doc.i.in
> +    The fields of residuals."
```suggestion
    The sample of residuals fields."
```

2023-10-02 19:47 UTC, mbaudin47 approved these changes

2023-10-03 07:35 UTC, merged