Update KarhunenLoeveValidation_doc.i.in
openturns/openturns pull request #2382
Opened 2023-09-06 10:15 UTC by adutfoy

Detailed the drawValidation method.

2023-09-07 06:49 UTC, jschueller approved these changes

2023-09-09 15:05 UTC, mbaudin47 requested changes
Thank you for the bug fix! I feel that rephrasing the sentence might improve its meaning.

2023-09-09 15:05 UTC, mbaudin47 commented on python/src/KarhunenLoeveValidation_doc.i.in
> +point of the mesh. One graph is drawn for each marginal of the field.
```suggestion
For each marginal of the fields in the sample, we draw the value of the observed field depending on
the value of the Karhunen-Loève reduced field (built from the real field thanks to the projection and lift functions) at each
node of the mesh. One graph is drawn for each marginal of the field.
```

2023-09-18 14:59 UTC, sofianehaddad commented on python/src/KarhunenLoeveValidation_doc.i.in
> +the value of the Karhunen-Loève reduced field (built from the real field thanks to the projection and lift functions) at each
```suggestion
the value of the Karhunen-Loève reduced field (built from the observed field thanks to the projection and lift functions) at each
```

2023-10-24 05:54 UTC, sofianehaddad approved these changes

2023-10-24 06:41 UTC, merged