Update SobolIndicesAlgorithmImplementation_doc.i.in
openturns/openturns pull request #2398
Opened 2023-09-25 19:45 UTC by mbaudin47

Clarifies the purpose of getSecondOrderIndices

2023-09-28 06:13 UTC, m-balesdent approved these changes

2023-09-28 06:41 UTC, jschueller approved these changes

2023-09-28 13:29 UTC, sofianehaddad commented on python/src/SobolIndicesAlgorithmImplementation_doc.i.in
> +For any pair of indices :math:`i, j \in \{1, ..., n_x\}`,
$i \neq j$

2023-10-25 13:03 UTC, josephmure requested changes

2023-10-25 13:03 UTC, josephmure commented on python/src/SobolIndicesAlgorithmImplementation_doc.i.in
> +Inversely, if the closed Sobol' indice :math:`S_{\{i, j\}}^{\operatorname{cl}}` is known,
```suggestion
Conversely, if the closed Sobol' index :math:`S_{\{i, j\}}^{\operatorname{cl}}` is known,
```

2023-10-31 16:30 UTC, mbaudin47 commented on python/src/SobolIndicesAlgorithmImplementation_doc.i.in
> +For any pair of indices :math:`i, j \in \{1, ..., n_x\}`,
Ok, fixed at 1649d580a7bce2626df7e4e5657f65cdda7d3710

2024-03-20 09:18 UTC, mbaudin47 commented
@josephmure : please consider this PR, since I took your suggestions into account.

2024-03-20 10:40 UTC, josephmure commented on python/src/SobolIndicesAlgorithmImplementation_doc.i.in
> +this method computes the Sobol' interaction indice between :math:`i` and :math:`j`:
```suggestion
this method computes the Sobol' interaction index between :math:`i` and :math:`j`:
```

2024-03-20 19:16 UTC, mbaudin47 commented
@josephmure : please consider this PR, since I took your suggestions into account.

2024-03-20 23:33 UTC, josephmure commented on python/src/SobolIndicesAlgorithmImplementation_doc.i.in
> +then the interaction Sobol' indice can be computed from the equation:
```suggestion
then the interaction Sobol' index can be computed from the equation:
```

2024-03-22 15:33 UTC, josephmure approved these changes

2024-03-22 15:40 UTC, merged