Add missing examples
openturns/openturns pull request #2410
Opened 2023-09-30 22:35 UTC by mbaudin47

2023-10-01 17:11 UTC, mbaudin47 commented on python/src/LARS_doc.i.in
> +...)
```suggestion
... )
```

2023-10-19 07:07 UTC, regislebrun approved these changes
Nice examples. Some casts are unnecessary, and some loops could be avoided but nothing blocking.

2023-10-19 07:07 UTC, regislebrun commented on python/src/LARS_doc.i.in
> +>>> polynomialCollection = ot.PolynomialFamilyCollection(im.dim)
You can use:
```
polynomialCollection = [ot.LegendreFactory()]*im.dim
```

2023-10-19 07:07 UTC, regislebrun commented on python/src/LARS_doc.i.in
> +>>> productBasis = ot.OrthogonalBasis(
No need to cast `ot.OrthogonalProductPolynomialFactory` into `ot.OrthogonalBasis`.
If you use the linear enumeration you don't even have to pass it to the constructor of `ot.OrthogonalProductPolynomialFactory` (but you may want to make it explicit)

2023-10-19 07:07 UTC, regislebrun commented on python/src/LeastSquaresMethod_doc.i.in
> +>>> phis = []
```
phis = [ot.SymbolicFunction(['x'], ['x^' + str(j + 1)]) for j in range(basisSize)]
```

2023-10-19 07:07 UTC, regislebrun commented on python/src/SparseMethod_doc.i.in
> +>>> phis = []
```
phis = [ot.SymbolicFunction(['x'], ['x^' + str(j + 1)]) for j in range(basisSize)]
```

2023-10-25 12:49 UTC, josephmure requested changes

2023-10-25 12:49 UTC, josephmure commented on python/src/DesignProxy_doc.i.in
> +...     X[i, 0] = i + 1.0
```suggestion
>>> X = ot.Sample.BuildFromPoint(range(sampleSize))
```

2023-10-25 12:49 UTC, josephmure commented on python/src/KFold_doc.i.in
> +>>> indices = list(range(len(basis)))
```suggestion
>>> indices = [0]
```
I get you want to be generic but this is overkill to me...

2023-10-25 12:49 UTC, josephmure commented on python/src/LeastSquaresMethod_doc.i.in
> +>>> X = ot.Sample(sampleSize, 1)
Same comments as before.

2023-10-25 12:49 UTC, josephmure commented on python/src/LeastSquaresMethod_doc.i.in
> +... ).getRealization()
```suggestion
>>> normal = ot.Normal([1.0] * sampleSize, [0.1] * sampleSize)
>>> y = normal.getRealization()
```

2023-10-25 12:49 UTC, josephmure commented on python/src/SparseMethod_doc.i.in
> +>>> X = ot.Sample(sampleSize, 1)
Same as before.

2023-10-30 21:41 UTC, mbaudin47 commented on python/src/DesignProxy_doc.i.in
> +...     X[i, 0] = i + 1.0
Not exactly. This corresponds exactly:
```suggestion
>>> X = ot.Sample.BuildFromPoint(range(1, 1 + sampleSize))
```
@josephmure : Do you agree?

2023-10-30 21:43 UTC, mbaudin47 commented on python/src/LARS_doc.i.in
> +...    )
```suggestion
>>> polynomialCollection = [ot.LegendreFactory()] * im.dim
```

2023-10-30 21:44 UTC, mbaudin47 commented on python/src/LARS_doc.i.in
> +...)
```suggestion
>>> productBasis = ot.OrthogonalProductPolynomialFactory(polynomialCollection, enumerateFunction)
```

2023-10-30 21:45 UTC, mbaudin47 commented on python/src/LeastSquaresMethod_doc.i.in
> +...     X[i, 0] = i + 1.0
```suggestion
>>> X = ot.Sample.BuildFromPoint(range(1, 1 + sampleSize))
```

2023-10-30 21:45 UTC, mbaudin47 commented on python/src/LeastSquaresMethod_doc.i.in
> +...     phis.append(ot.SymbolicFunction(['x'], ['x^' + str(j + 1)]))
```suggestion
>>> phis = [ot.SymbolicFunction(['x'], ['x^' + str(j + 1)]) for j in range(basisSize)]
```

2023-10-30 21:47 UTC, mbaudin47 commented on python/src/SparseMethod_doc.i.in
> +...     X[i, 0] = i + 1.0
```suggestion
>>> X = ot.Sample.BuildFromPoint(range(1, 1 + sampleSize))
```

2023-10-30 21:47 UTC, mbaudin47 commented on python/src/SparseMethod_doc.i.in
> +...     phis.append(ot.SymbolicFunction(['x'], ['x^' + str(j + 1)]))
```suggestion
>>> phis = [ot.SymbolicFunction(['x'], ['x^' + str(j + 1)]) for j in range(basisSize)]
```

2023-10-31 13:16 UTC, josephmure approved these changes
OK for me after this change.

2023-10-31 13:16 UTC, josephmure commented on python/src/SparseMethod_doc.i.in
> +... ).getRealization()
```suggestion
>>> normal = ot.Normal([1.0] * sampleSize, [0.1] * sampleSize)
>>> y = normal.getRealization()
```

2023-10-31 13:24 UTC, merged