Update FunctionalChaosSobolIndices_doc.i.in
openturns/openturns pull request #2414
Opened 2023-10-03 14:47 UTC by mbaudin47

Document the FunctionalChaosSobolIndices key of the ResourceMap.

2023-10-17 12:11 UTC, jschueller approved these changes

2023-10-25 12:32 UTC, josephmure requested changes
A necessary precision to the doc, thanks!

2023-10-25 12:32 UTC, josephmure commented on python/src/FunctionalChaosSobolIndices_doc.i.in
> +If a multi-indice has a part of variance which is lower than some
```suggestion
If a multi-index accounts for a smaller part of the variance than some
```

2023-11-08 15:03 UTC, josephmure approved these changes

2023-11-08 15:27 UTC, merged