Update ranking_src.rst
openturns/openturns pull request #2430
Opened 2023-10-15 15:09 UTC by mbaudin47

Fixed wrong definition of SRC indices.
Create new squared SRC indices definition (the current text lets this undefined). Made clear that the validation of the linear model is mandatory (not optional, as the current text suggests). Made the link to the `CorrelationAnalysis` class.
Create new bibliographic references (the current text has no one).

2023-10-19 06:30 UTC, regislebrun approved these changes

2023-10-25 07:57 UTC, josephmure requested changes
Good job, only a few details need fixing.

2023-10-25 07:57 UTC, josephmure commented on python/doc/theory/reliability_sensitivity/ranking_src.rst
> +where :math:`(a_i)_{i = 0, 1, ..., n_X}` are constant parameters,
```suggestion
where :math:`(a_i)_{i = 0, 1, ..., n_X}` are constant parameters and
```

2023-10-25 07:57 UTC, josephmure commented on python/doc/theory/reliability_sensitivity/ranking_src.rst
> +:math:`\Var{X_i} = \sigma_i^2`, the variance of :math:`Y` can be
```suggestion
:math:`\Var{X_i}`, the variance of :math:`Y` can be
```
The $\sigma_i$ notation is not used elsewhere, so no need to introduce it.

2023-10-25 07:57 UTC, josephmure commented on python/doc/theory/reliability_sensitivity/ranking_src.rst
>  The SRC coefficients are defined as the estimators :math:`\widehat{C}_i`
```suggestion
The SRC coefficients are defined as the estimators :math:`\widehat{\operatorname{SRC}}_i`
```

2023-10-25 07:57 UTC, josephmure commented on python/doc/theory/reliability_sensitivity/ranking_src.rst
> +this index is more a measure of the linear relationship between the input and the
```suggestion
this index is rather a measure of the linear relationship between the input and the
```

2023-10-31 07:05 UTC, jschueller commented
@josephmure if you would approve I could merge it

2023-10-31 13:07 UTC, josephmure approved these changes

2023-10-31 13:19 UTC, merged