misc bugs
openturns/openturns pull request #2476
Opened 2023-11-16 20:40 UTC by jschueller

- IntervalMesher: Fix diamond=True in dim=3 (#1670)
![diamond](https://github.com/openturns/openturns/assets/3832365/1b18630f-fc15-44f2-8927-d1ee4cf33769)

2023-12-11 09:53 UTC, jschueller commented
TODO: move to experimental

2023-12-11 17:30 UTC, regislebrun approved these changes
PosteriorDistribution needs a full rework, otherwise good to go

2024-01-05 14:54 UTC, josephmure requested changes

2024-01-05 14:54 UTC, josephmure commented on python/src/ConditionalDistribution_doc.i.in
>  %feature("docstring") OT::ConditionalDistribution::getConditionedDistribution
The formatting is weird: why are the returns bold?

![image](https://github.com/openturns/openturns/assets/31989332/fe438034-b136-40f9-abcb-d0b97f8bb30a)

2024-01-05 14:54 UTC, josephmure commented on python/src/ConditionalDistribution_doc.i.in
>        :math:`g: \Rset^p \rightarrow \Rset^q`, where :math:`p` is the dimension of
```suggestion
linkFunction : :class:`~openturns.Function`
      the function :math:`g: \Rset^p \rightarrow \Rset^q`, where :math:`p` is the dimension of
```

2024-01-05 14:54 UTC, josephmure commented on python/src/ConditionalDistribution_doc.i.in
>  %feature("docstring") OT::ConditionalDistribution::setConditionedDistribution
Same formatting error

![image](https://github.com/openturns/openturns/assets/31989332/386bf2fd-1ec1-473a-a77d-460b251adcec)

2024-01-05 14:54 UTC, josephmure commented on python/src/PosteriorDistribution_doc.i.in
>  %feature("docstring") OT::PosteriorDistribution
The experimental warning is missing.

2024-01-05 14:54 UTC, josephmure commented on python/src/PosteriorDistribution_doc.i.in
> +    The conditional distribution of density :math:`f_{\vect{X}}(\vect{x}) = \int f_{\vect{X}|\vect{\Theta}=\vect{y}}(\vect{x}|\vect{y}) f_{\vect{Y}}(\vect{y})\di{\vect{y}}`.
```suggestion
    The distribution of density :math:`f_{\vect{X}}(\vect{x}) = \int f_{\vect{X}|\vect{\Theta}=\vect{y}}(\vect{x}|\vect{y}) f_{\vect{Y}}(\vect{y})\di{\vect{y}}`.
```
I know the class is named that way but the name is badly chosen, so let's try to keep the confusion to a minimum.

2024-01-05 14:54 UTC, josephmure commented on python/src/PosteriorDistribution_doc.i.in
> +    f_{\vect{Y}|\vect{X}=\vect{x}}(\vect{y}) = f_{\vect{Y}}(\vect{y})\prod_{i=1}^n f_{X|\vect{\Theta}=\vect{y}}(x_i)\frac{1}{\prod_{i=1}^n f_{X}(x_i)}
```suggestion
    f_{\vect{Y}|\vect{X}=\vect{x}}(\vect{y}) = \frac{f_{\vect{Y}}(\vect{y})\prod_{i=1}^n f_{X|\vect{\Theta}=\vect{y}}(x_i)}{\int f_{\vect{Y}}(\vect{y}')\prod_{i=1}^n f_{X|\vect{\Theta}=\vect{y}'}(x_i) d \vect{y}'}
```
Sorry for the confusion, but this is the correct formula.

2024-01-08 08:30 UTC, jschueller commented
can I merge this soon @josephmure ? else it will go to 1.23

2024-01-08 10:51 UTC, josephmure approved these changes

2024-01-08 10:53 UTC, josephmure commented
Yes, by all means, do merge it! @mbaudin47 will not have time to review this PR.

2024-01-08 11:21 UTC, merged