Use default colors when adding a graph to another graph
openturns/openturns pull request #2491
Opened 2023-11-24 08:22 UTC by josephmure

# Goal

Build upon PR #2422 by expanding the use of default colors : 

- PR #2422 applies a default color to a Drawable when it is added to a Graph (provided its color has not been previously explicitly set)
- This PR does the same  to all Drawables of a Graph when that Graph is added to another.

# Implementation

This PR adds a protected method to DrawableImplementation: `setColor(String color, Bool isExplicitlySet)`

This protected method is used by the friend class GraphImplementation to set the color and the isExplicitlySet_ attribute at the same time. Allows is to unexplicitly set colors when it applies the default palette.

2024-02-08 12:12 UTC, mbaudin47 commented
To make the review easier, I write below a list of the examples which are changed by the PR:
- [plot_estimate_non_parametric_distribution.html](https://openturns.github.io/openturns/latest/auto_data_analysis/distribution_fitting/plot_estimate_non_parametric_distribution.html)
- [plot_overfitting_model_selection.html](https://openturns.github.io/openturns/latest/auto_meta_modeling/general_purpose_metamodels/plot_overfitting_model_selection.html)

2024-02-08 14:05 UTC, mbaudin47 requested changes
Thank you for that PR: it is an excellent addition.
I feel, however, that one of the examples you updated can be made even better. To improve on this, I created a PR on your repo:

https://github.com/josephmure/openturns/pull/12

Please consider including it and see how it improves the examples from your point of view.

2024-02-08 22:36 UTC, mbaudin47 approved these changes

2024-03-06 22:26 UTC, josephmure commented
@jschueller Could you please review?

2024-03-07 07:55 UTC, jschueller commented on lib/src/Base/Graph/GraphImplementation.cxx
> +    drawable.getImplementation()->setColor(DrawableImplementation::BuildDefaultPalette(drawableCount + 1)[drawableCount], false);
this will bypass the copyonwrite and modify the original as well

2024-03-07 07:55 UTC, jschueller commented on lib/src/Base/Graph/GraphImplementation.cxx
> +      drawable.getImplementation()->setColor(palette[i], false);
here too

2024-03-19 14:59 UTC, merged