Misc
openturns/openturns pull request #2635
Opened 2024-04-29 15:30 UTC by jschueller

2024-04-30 18:51 UTC, regislebrun requested changes

2024-04-30 19:42 UTC, jschueller commented on lib/src/Uncertainty/Bayesian/RandomWalkMetropolisHastings.cxx
> +  if (!((cdf0 > proposal.getCDFEpsilon()) && (cdf0 < 1.0 - proposal.getCDFEpsilon())))
like distribution-qmin/qmax ?

2024-04-30 21:00 UTC, regislebrun commented on lib/src/Uncertainty/Bayesian/RandomWalkMetropolisHastings.cxx
> +  if (!((cdf0 > proposal.getCDFEpsilon()) && (cdf0 < 1.0 - proposal.getCDFEpsilon())))
Yes, even if these bounds have been introduced to select automatically the interval on which the PDF of 1D distributions are drawn, see https://github.com/openturns/openturns/blob/d21f6c118286cf7c24bc0d7be842990bdc8a891b/lib/src/Uncertainty/Model/DistributionImplementation.cxx#L3748

2024-05-01 07:22 UTC, jschueller commented on lib/src/Uncertainty/Bayesian/RandomWalkMetropolisHastings.cxx
> +  if (!((cdf0 > proposal.getCDFEpsilon()) && (cdf0 < 1.0 - proposal.getCDFEpsilon())))
ok

2024-05-02 07:33 UTC, merged