Last fixes before 1.23
openturns/openturns pull request #2652
Opened 2024-05-10 14:22 UTC by jschueller

- #2567 
- #2604 
- #2642

2024-05-11 09:27 UTC, mbaudin47 commented
It seems that there are unexpected errors in mingw. For example:
```
terminate called after throwing an instance of 'H5::FileIException'
```

2024-05-16 19:54 UTC, mbaudin47 approved these changes
Thank you for fixing the Kernel Smoothing description bug.

2024-06-04 10:35 UTC, sofianehaddad approved these changes

2024-06-04 11:14 UTC, regislebrun approved these changes
Ok so the DiscreteMarkovChain class is fixed locally, not by switching to the same internal and external representation of the transition matrix. The difficulty is to manage an internal change at the save/load level.

2024-06-05 07:25 UTC, josephmure requested changes

2024-06-05 07:25 UTC, josephmure commented on lib/src/Uncertainty/Distribution/HistogramFactory.cxx
> +  if (xMax == xMin) throw InvalidArgumentException(HERE) << "Error: cannot estimate an Histogram distribution from a constant sample.";
```suggestion
  if (!(xMax > xMin))
    throw InvalidArgumentException(HERE) << "Error: cannot estimate a Histogram distribution from a constant sample, here max value is " << xMax << " and min value is " << xMin;
```
To be NaN-safe + typo correction

2024-06-05 07:25 UTC, josephmure commented on lib/src/Uncertainty/Distribution/HistogramFactory.cxx
> +    throw InvalidArgumentException(HERE) << "Cannot build an Histogram distribution from a sample of size < 2";
```suggestion
    throw InvalidArgumentException(HERE) << "Cannot build a Histogram distribution from a sample of size < 2";
```

2024-06-05 07:25 UTC, josephmure commented on lib/src/Uncertainty/Distribution/HistogramFactory.cxx
> +    throw InvalidArgumentException(HERE) << "Cannot estimate an Histogram distribution from a constant sample.";
```suggestion
  if (!(xMax > xMin))
    throw InvalidArgumentException(HERE) << "Error: cannot estimate a Histogram distribution from a constant sample, here max value is " << xMax << " and min value is " << xMin;
```
To be NaN-safe + typo correction

2024-06-05 07:37 UTC, josephmure commented on lib/src/Uncertainty/Distribution/TrapezoidalFactory.cxx
> +  if (xMin == xMax) throw InvalidArgumentException(HERE) << "Error: cannot estimate a Trapezoidal distribution from a constant sample.";
```suggestion
  if (!(xMax > xMin))
    throw InvalidArgumentException(HERE) << "Error: cannot estimate a Trapezoidal distribution from a constant sample, here max value is " << xMax << " and min value is " << xMin;
```
To be NaN-safe + more explicit error message

2024-06-05 08:51 UTC, josephmure approved these changes
Good to go after this last change.

2024-06-05 08:51 UTC, josephmure commented on lib/src/Uncertainty/Distribution/HistogramFactory.cxx
> +  if (xMax == xMin) throw InvalidArgumentException(HERE) << "Error: cannot estimate an Histogram distribution from a constant sample.";
```suggestion
  if (!(xMax > xMin))
    throw InvalidArgumentException(HERE) << "Error: cannot estimate a Histogram distribution from a constant sample, here max value is " << xMax << " and min value is " << xMin;
```

I forgot that one.

2024-06-05 09:44 UTC, merged