Fix posterior distribution
openturns/openturns pull request #2838
Opened 2024-11-28 14:23 UTC by regislebrun

This distribution has been created a long time ago, and has never been thoroughly tested. Most of the methods was incorrect from a mathematical point of view. They have been updated and now the distribution is mostly usable. The main points to fix are:
  * to enhance the computation of the log-normalization factor in order to work with large samples of observations
  * to share the ratio of uniforms algorithm with PointConditionalDistribution
  * to implement more methods, such as the isoprobabilistic transformations

2024-11-28 14:46 UTC, jschueller commented
I suggest to try to use DistributionValidation in the PosteriorDistribution python test, failing parts can still be avoided with the skip methods

2024-11-28 15:16 UTC, jschueller commented on lib/src/Uncertainty/Distribution/PosteriorDistribution.cxx
> +    }
TODO: move this code in a common location

2024-12-04 15:58 UTC, jschueller commented on lib/test/t_PosteriorDistribution_std.cxx
> +      fullprint << "entropy (MC)=" << -distribution.computeLogPDF(distribution.getSample(10000)).computeMean()[0] << std::endl;
seems the CI is not too happy here on macos, maybe try to reduce digits ?

2024-12-12 15:54 UTC, jschueller commented on python/test/t_RatioOfUniforms_std.py
> +
this test is not enabled in cmakelists (codecov cannot see it :)

2025-01-20 07:33 UTC, jschueller commented on python/src/RatioOfUniforms_doc.i.in
> +>>> ratioOfU = otexp.RatioOfUniforms(Normal())"
ot.Normal

2025-01-22 09:13 UTC, regislebrun commented on python/test/t_RatioOfUniforms_std.py
> +
Fixed

2025-01-22 09:14 UTC, regislebrun commented on lib/test/t_PosteriorDistribution_std.cxx
> +      fullprint << "entropy (MC)=" << -distribution.computeLogPDF(distribution.getSample(10000)).computeMean()[0] << std::endl;
Fixed

2025-01-22 09:14 UTC, regislebrun commented on python/src/RatioOfUniforms_doc.i.in
> +>>> ratioOfU = otexp.RatioOfUniforms(Normal())"
Fixed

2025-01-22 13:02 UTC, jschueller commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +# in all these cases.
weird, according to the graphs r=0.5 leads to tau=0.265 which is better than the tau=0.227 for r=1

2025-01-22 13:03 UTC, jschueller commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +
imho we should stick to lowercase file names for examples

2025-01-22 13:15 UTC, jschueller commented on python/src/RatioOfUniforms_doc.i.in
> +%feature("docstring") OT::RatioOfUniforms::setOptimizationAlgorithm
getOptimizationAlgorithm doc is missing

2025-01-22 13:21 UTC, jschueller commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +# %%
one must call ResourceMap.Reset since you're modifying the resourcemap at the top of the example

2025-01-22 13:24 UTC, jschueller commented on lib/src/Uncertainty/Model/openturns/RatioOfUniforms.hxx
> +  RatioOfUniforms(const Distribution & distribution);
explicit

2025-01-22 13:27 UTC, jschueller commented on lib/src/Uncertainty/Distribution/PosteriorDistribution.cxx
> +  isParallel_ = flag1 && flag2 && flag3;
```
isParallel_ = deconditionedDistribution_.getLinkFunction().getEvaluation().getImplementation()->isParallel()
               && deconditionedDistribution_.getConditioningDistribution().getImplementation()->isParallel()
               && deconditionedDistribution_.getConditionedDistribution().getImplementation()->isParallel();
```

2025-01-22 13:33 UTC, jschueller commented on python/src/RatioOfUniforms_doc.i.in
> +>>> ratioOfU = otexp.RatioOfUniforms(ot.Normal())"
```
>>> ratioOfU.initialize() # doctest: +SKIP
>>> x = ratioOfU.getRealization() # doctest: +SKIP
```

2025-01-22 13:37 UTC, jschueller approved these changes
great!

2025-01-23 09:07 UTC, mbaudin47 requested changes

2025-01-23 09:07 UTC, mbaudin47 commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +# Then, :math:`X = \left(\dfrac{V}{U^r}\right)` is a random variable on
There is no need for the parentheses here:
```suggestion
# Then, :math:`X = \dfrac{V}{U^r}` is a random variable on
```

2025-01-23 09:09 UTC, mbaudin47 requested changes

2025-01-23 09:09 UTC, mbaudin47 commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +#                    & = \left[0, u_{sup} \right] \times [v_{inf}, v_{sup}]
The second pair of square brackets are not large enough.
```suggestion
#    \left[ \inf_{x} x f(x)^{\frac{1}{1+r}} ,  \sup_{x} x f(x)^{\frac{1}{1+r}} \right] \\
#                    & = \left[0, u_{sup} \right] \times [v_{inf}, v_{sup}]
```

2025-01-23 09:47 UTC, jschueller commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +g_UV.setTitle(r'$\log f(x) = \log(\cos(x)) + x$, $r = $%.3g' % ratioAlgo.getR() + r', $\tau = $%.3g' % ratioAlgo.getAcceptanceRatio())
use raw f-strings: 
```
g_UV.setTitle(fr"$\log f(x) = \log(\cos(x)) + x$, $r = ${ratioAlgo.getR():.3g} , $\tau = ${ratioAlgo.getAcceptanceRatio():.3g}$")
```

2025-01-23 09:47 UTC, jschueller commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +g_XY.setTitle(r'$r = $%.3g' % ratioAlgo.getR() + r', $\tau = $%.3g' % ratioAlgo.getAcceptanceRatio())
here too

2025-01-23 10:18 UTC, mbaudin47 requested changes

2025-01-23 10:18 UTC, mbaudin47 commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +#    \log f(x) = \log(\cos(x)) + x,  \quad  x \in [-\dfrac{\pi}{2}, \dfrac{\pi}{2}]
![image](https://github.com/user-attachments/assets/766e5566-b7ab-49e7-a744-d8533e380034)

```suggestion
#    \log f(x) = \log(\cos(x)) + x,  \quad  x \in \left[-\dfrac{\pi}{2}, \dfrac{\pi}{2} \right]
```

2025-01-23 10:25 UTC, mbaudin47 requested changes

2025-01-23 10:25 UTC, mbaudin47 commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +print('New acceptance ratio = ', ratioAlgo.getAcceptanceRatio())
The value returned by getAcceptanceRatio() seems to be greater than 1:

![image](https://github.com/user-attachments/assets/5efdfbf9-ee73-412a-ae57-0b9da64e4bc2)

2025-01-23 10:29 UTC, mbaudin47 requested changes

2025-01-23 10:29 UTC, mbaudin47 commented on python/src/RatioOfUniforms_doc.i.in
> +This algorithm samples a multivariate distribution whose probability density probability is known up to a multiplicative factor.
Please give the bibliographic references of the algorithm.

2025-01-23 10:37 UTC, mbaudin47 requested changes

2025-01-23 10:37 UTC, mbaudin47 commented on lib/src/Base/Common/ResourceMap.cxx
> +  addAsUnsignedInteger("RatioOfUniforms-CandidateNumber", 10000);
Given that this is used as the sample size of a Sobol' sequence, it might be interesting to select a base-2 integer, e.g. $2^{13} =8192$ or $2^{14}=16384$.

2025-01-25 17:51 UTC, regislebrun commented
@jschueller I added new methods to RatioOfUniform and I have troubles making swig happy with them:
  * `Collection<MultiStart> initialize()` returns a new kind of Collection and I don't know how to SWIG it. I tried to add `%template(MultiStartCollection) OT::Collection<OT::MultiStart>;` to `RatioOfUniforms.i`, failed;
  * `Sample RatioOfUniforms::getSampleWithTryNumber(const UnsignedInteger size, UnsignedInteger & tryNumber) const` where the second argument is modified by the method. I added
  ```
  %typemap(in, numinputs=0) OT::UnsignedInteger & tryNumberOut ($*ltype temp) %{ temp = OT::UnsignedInteger(); $1 = &temp; %}
%typemap(argout) OT::UnsignedInteger & tryNumberOut %{ $result = OT::AppendOutput($result, PyLong_FromUnsignedLong(*$1)); %}
  ```
in `RatioOfUniforms.i` but no success...

If you have some advices to make it work, I will be happy to improve my SWIG skills!

2025-01-25 18:28 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +# in all these cases.
Not an actual problem, as the point is to check if the acceptance ratio for r==1 is close to the optimum (let's say within 30%)

2025-01-27 08:14 UTC, jschueller commented
are we sure we want to return a list of MultiStart and not only the list of OptimResult ?

2025-01-27 13:24 UTC, jschueller commented on lib/src/Uncertainty/Distribution/JointDistribution.cxx
> +  Bool sameNu = true;
unused

2025-01-27 14:35 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +
done

2025-01-27 14:35 UTC, regislebrun commented on python/src/RatioOfUniforms_doc.i.in
> +%feature("docstring") OT::RatioOfUniforms::setOptimizationAlgorithm
done

2025-01-27 14:40 UTC, regislebrun commented on lib/src/Uncertainty/Distribution/PosteriorDistribution.cxx
> +  isParallel_ = flag1 && flag2 && flag3;
done

2025-01-27 14:44 UTC, regislebrun commented on python/src/RatioOfUniforms_doc.i.in
> +>>> ratioOfU = otexp.RatioOfUniforms(ot.Normal())"
done

2025-01-27 14:51 UTC, regislebrun commented on lib/src/Uncertainty/Model/openturns/RatioOfUniforms.hxx
> +/**
done

2025-01-27 14:52 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +# Then, :math:`X = \left(\dfrac{V}{U^r}\right)` is a random variable on
done

2025-01-27 14:55 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +#                    & = \left[0, u_{sup} \right] \times [v_{inf}, v_{sup}]
done

2025-01-27 15:01 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +g_UV.setTitle(r'$\log f(x) = \log(\cos(x)) + x$, $r = $%.3g' % ratioAlgo.getR() + r', $\tau = $%.3g' % ratioAlgo.getAcceptanceRatio())
done

2025-01-27 15:01 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +    g_XY.setTitle(r'$\log f(x) = \log(\cos(x)) + x$, $r = $%.3g' % ratioAlgo.getR() + r', $\tau = $%.3g' % ratioAlgo.getAcceptanceRatio())
done

2025-01-27 15:03 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +#    \log f(x) = \log(\cos(x)) + x,  \quad  x \in [-\dfrac{\pi}{2}, \dfrac{\pi}{2}]
done

2025-01-27 16:19 UTC, regislebrun commented on lib/src/Uncertainty/Distribution/JointDistribution.cxx
> +  Bool sameNu = true;
done

2025-01-27 16:20 UTC, regislebrun commented
> * are we sure we want to return a list of MultiStart and not only the list of OptimResult ?
Yes, in order to have access to the starting points for supU, infV and supV.

2025-01-27 16:35 UTC, regislebrun commented on lib/src/Base/Common/ResourceMap.cxx
> +  addAsUnsignedInteger("RatioOfUniforms-CandidateNumber", 10000);
True! It has been changed to 8192.

2025-01-27 16:37 UTC, regislebrun commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +print('New acceptance ratio = ', ratioAlgo.getAcceptanceRatio())
Fixed, the maximum multistart parameter was not taken into account and only one candidate was used by the optimization algorithm.

2025-01-27 20:07 UTC, regislebrun commented on python/src/RatioOfUniforms_doc.i.in
> +This algorithm samples a multivariate distribution whose probability density probability is known up to a multiplicative factor.
done

2025-01-27 20:52 UTC, regislebrun commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratioOfUniforms_exploitation.py
> +g_XY.setTitle(r'$r = $%.3g' % ratioAlgo.getR() + r', $\tau = $%.3g' % ratioAlgo.getAcceptanceRatio())
done

2025-01-28 07:38 UTC, jschueller commented on lib/src/Uncertainty/Model/RatioOfUniforms.cxx
> +<<<<<<< HEAD
bad merge ?

2025-01-28 08:04 UTC, regislebrun commented on lib/src/Uncertainty/Model/RatioOfUniforms.cxx
> +<<<<<<< HEAD
I tried to fix it a dozen times, but finally I had to switch commits to fix it definitely... Git, what a strange thing to me...

2025-02-07 15:11 UTC, adutfoy commented
This PR add the following documentation:

- RatioOfUniforms: API, one new example, one improved example,
- PointConditionalDistribution: general formula and range computing strategies (PR #2844)

2025-02-13 07:19 UTC, l-brevault commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +# We can change the sampler of that new distribution by implementing the method *getSample* and *getRealization* as follows:
here we could refer to Ratio of Uniforms:

"We can change the sampler of that new distribution relying on Ratio of Uniforms algorithm by implementing the method ..."

2025-02-13 07:20 UTC, l-brevault commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +# By default, the parameter :math:`r=1`. We can get the associated acceptance ratio:
I would add a "see the documentation for more information on the parameter purpose"

2025-02-13 07:20 UTC, l-brevault commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +# the documenttaion of :class:`~openturns.experimental.RatioOfUniforms`):
documentation

2025-02-13 07:20 UTC, l-brevault commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +
I am not sure to understand what we conclude from changing the parameter r from r=1 to r=0.5 considering the acceptance ratio changing from 0.100 to 0.111 ? 
Should we add a sentence to clarify the consequences of changing r here ?

2025-02-13 07:20 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# Let :math:`(U, V)` be a random variable uniformly distributed on :math:`A_{f,r}`.
a set of random variables or a random variable vector ?

2025-02-13 07:20 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# This allows one to sample uniformly the domain :math:`A_{f,r}` by rejection sampling inside
and by rejection

2025-02-13 07:20 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +#    \partial A_{f,r}  = \left\{ (u,v) = \left( f(x)^{\dfrac{1}{1+r}}, x f(x)^{\dfrac{r}{1+r}} \right),
\frac{1}{1+r}  and \frac{r}{1+r}   to avoid the large exponant ?

2025-02-13 07:21 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# Then we have:
Then,

2025-02-13 07:21 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +#    \varphi(A_{f,r}) = \left\{ (x,y) \, |\, x \in \Rset, 0 \leq y \leq f(x)^{\dfrac{1}{1+r}} \right\}
idem ?

2025-02-13 07:21 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# sphinx_gallery_thumbnail_number = 1
go to the line to avoid it to follow the previous sentence

2025-02-13 07:21 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +
maybe add a sentence of analysis based on the plots on the influence of the parameter r on the shape of the boundaries to help the reader to understand the role of this parameter ?

2025-02-13 07:21 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +
idem adding a short sentence of analysis of the above plot on the accpetance ratio as a function of r would help the reader that are not familiar with such algorithm and the key role of the parameter r

2025-02-13 07:21 UTC, l-brevault commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# points are selected scrolling through  the Sobol low discrepance sequence in dimension :math:`\inputDim =  1`
Sobol'

2025-02-13 07:21 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +   Function :math:`\log F` such that :math:`f = F\, 1_{I}`  is proportional to the PDF :math:`p` we want to sample.
In the rest of the documentation (see for instance Subset or NAIS) the indicator function is in "bold":  \mathbf{1}

2025-02-13 07:21 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +    Flag telling if the input *logUnscaledPDF* is such that :math:`f = F\, 1_{I}` is an actual PDF of a distribution.
idem bold

2025-02-13 07:21 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +    f(\vect{x}) = F(\vect{x})\, 1_{I}\quad \forall \vect{x}  \in I
idem bold

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +Let :math:`(U, V_1, \dots, V_\inputDim)` be a random variable uniformly distributed on  :math:`A_{f,r}`.
a set of random variables ? or a random variable vector ?

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +:math:`\vect{x} \rightarrow x_if(\vect{x})^{\frac{1}{1+r\inputDim}}` for all :math:`i` are bounded, then the domain
for all i \in [1,d] ?

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +    \tilde{A}_{f,r} & = \left[0, \sup_{\vect{x}} f(\vect{x})^{\frac{1}{1+r\inputDim}} \right] \times \prod_i
\prod_{i=1}^d

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +                    & = [0, u_{sup}] \times \prod_{i=1}^d [v_{inf, i}, v_{sup, i}]
I guess that u_{sup} = \sup_{\vect{x}} f(\vect{x})^{\frac{1}{1+r\inputDim}

maybe we need to define the notation u_{sup}, v_{inf, i}, v_{sup, i} or at least say that these terms directly correspond to the above equation terms ?

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +such that :math:`f(\vect{x}_0)>0`. Such points are found by scrolling through a Sobol multivariate
Sobol'

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +- *RatioOfUniforms-CandidateNumber*: maximum number of points of the Sobol low discrepancy sequence of dimension
Sobol'

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +  Function :math:`\log F` where :math:`F\, 1_{I} \propto p`, the PDF we want to sample.
\mathbf{1}

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +entry *RatioOfUniforms-MaximumMultistart*, a new point of the Sobol low
Sobol'

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +points of the Sobol sequence is :math:`n`. If no starting point has been
idem Sobol'

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +entry *RatioOfUniforms-MaximumMultistart*, a new point of the Sobol low
Sobol'

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +points of the Sobol sequence is :math:`n`. If no starting point has been
idem

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +   Function :math:`\log F` such that :math:`f = F\, 1_{I}`  is proportional to the PDF :math:`p` we want to sample."
\mathbf{1}

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +As :math:`p \propto f = F\, 1_I`, then :math:`p = 0` outside :math:`I`."
idem

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +accepRatio : float, :math:`0 \leq \tau_{accept} \leq 1`,
Should it be acceptRatio ?

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +The acceptance ratio is computed at the initialization of the class by the ethod *initialize*, according to :eq:`acceptRatio` where :math:`c=1`
method

2025-02-13 07:22 UTC, l-brevault commented on python/src/RatioOfUniforms_doc.i.in
> +The methods returns a collection of multistart optimization algorithms containing:
the method

2025-02-14 07:41 UTC, jschueller commented
@regislebrun I opened https://github.com/regislebrun/openturns/pull/10

2025-02-14 14:07 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# sphinx_gallery_thumbnail_number = 1
yes...

2025-02-14 14:31 UTC, adutfoy commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +# We can draw the exact PDF and the PDF estimated from a sample generated by the Ratio of Uniforms algorithm.
yes... The text was wrong: I modified it! In that case, this is the generic sampler which is used.

2025-02-14 14:32 UTC, adutfoy commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +# We can change the sampler of that new distribution by implementing the method *getSample* and *getRealization* as follows:
yes.

2025-02-14 14:43 UTC, adutfoy commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +
I think the figure you want is exactly the third one: we draw the pdf estimated on a sample of size 100000 from the RoU sampler, compared to the exact one. 
The figure 4 draws the estimated pdf based on a sample of size 500 and size 100000 from the RoU sampler to show the convergence.

The figures 3 and 4 are directly using a RoU instance to sample the distribution. This is equivalent to the PythonDistribution that implements the RoU. Thus, the variables newDist_RoU and ratio_algo are doing the same job.
The difference is that a PythonDistribution gives access to numerous methods, more than just RoU class.

Do you agree?

2025-02-14 16:16 UTC, adutfoy commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +# By default, the parameter :math:`r=1`. We can get the associated acceptance ratio:
ok. I don't know how to create  link to another example....

2025-02-14 16:16 UTC, adutfoy commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +# the documenttaion of :class:`~openturns.experimental.RatioOfUniforms`):
yes

2025-02-14 16:35 UTC, adutfoy commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +
Yes I just wanted to show how to change the value of r....
I modified the text: I ploted the graph of $r \rightarrow \tau(r)$ to show that the default value $r=1$ is not so bad and that it is not worth changing its value.

2025-02-14 16:36 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# Let :math:`(U, V)` be a random variable uniformly distributed on :math:`A_{f,r}`.
random vector.....

2025-02-14 16:37 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# This allows one to sample uniformly the domain :math:`A_{f,r}` by rejection sampling inside
yes

2025-02-14 16:38 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +#    \partial A_{f,r}  = \left\{ (u,v) = \left( f(x)^{\dfrac{1}{1+r}}, x f(x)^{\dfrac{r}{1+r}} \right),
yes

2025-02-14 16:38 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# Then we have:
ok

2025-02-14 16:39 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +#    \varphi(A_{f,r}) = \left\{ (x,y) \, |\, x \in \Rset, 0 \leq y \leq f(x)^{\dfrac{1}{1+r}} \right\}
yes

2025-02-14 16:41 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +
yes... not easy to understand the utility of this parameter... I added a comment....

2025-02-14 16:45 UTC, adutfoy commented on python/doc/examples/probabilistic_modeling/random_vectors/plot_ratio_of_uniforms_exploitation.py
> +# points are selected scrolling through  the Sobol low discrepance sequence in dimension :math:`\inputDim =  1`
ok

2025-02-14 16:46 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +   Function :math:`\log F` such that :math:`f = F\, 1_{I}`  is proportional to the PDF :math:`p` we want to sample.
yes. I modified the text.

2025-02-14 16:47 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +    Flag telling if the input *logUnscaledPDF* is such that :math:`f = F\, 1_{I}` is an actual PDF of a distribution.
yes. I checked all the instances of 1_...

2025-02-14 16:47 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +    f(\vect{x}) = F(\vect{x})\, 1_{I}\quad \forall \vect{x}  \in I
yes

2025-02-14 16:48 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +Let :math:`(U, V_1, \dots, V_\inputDim)` be a random variable uniformly distributed on  :math:`A_{f,r}`.
random vector...

2025-02-14 16:52 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +    \tilde{A}_{f,r} & = \left[0, \sup_{\vect{x}} f(\vect{x})^{\frac{1}{1+r\inputDim}} \right] \times \prod_i
yes

2025-02-14 16:54 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +                    & = [0, u_{sup}] \times \prod_{i=1}^d [v_{inf, i}, v_{sup, i}]
yes. I precised the notations.

2025-02-14 16:54 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +- *RatioOfUniforms-CandidateNumber*: maximum number of points of the Sobol low discrepancy sequence of dimension
yes. I modified all the text.

2025-02-14 16:54 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +  Function :math:`\log F` where :math:`F\, 1_{I} \propto p`, the PDF we want to sample.
yes

2025-02-14 16:55 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +entry *RatioOfUniforms-MaximumMultistart*, a new point of the Sobol low
yes

2025-02-14 16:55 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +points of the Sobol sequence is :math:`n`. If no starting point has been
yes

2025-02-14 16:55 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +entry *RatioOfUniforms-MaximumMultistart*, a new point of the Sobol low
yes

2025-02-14 16:55 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +points of the Sobol sequence is :math:`n`. If no starting point has been
yes

2025-02-14 16:55 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +   Function :math:`\log F` such that :math:`f = F\, 1_{I}`  is proportional to the PDF :math:`p` we want to sample."
yes

2025-02-14 16:55 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +As :math:`p \propto f = F\, 1_I`, then :math:`p = 0` outside :math:`I`."
yes

2025-02-14 16:56 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +accepRatio : float, :math:`0 \leq \tau_{accept} \leq 1`,
yes

2025-02-14 16:56 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +The acceptance ratio is computed at the initialization of the class by the ethod *initialize*, according to :eq:`acceptRatio` where :math:`c=1`
yes

2025-02-14 16:57 UTC, adutfoy commented on python/src/RatioOfUniforms_doc.i.in
> +The methods returns a collection of multistart optimization algorithms containing:
yes

2025-02-14 16:59 UTC, adutfoy commented
@l-brevault : thanks for your remarks!
If you agree with my modifications, I propose to merge the PR because @jschueller  has approved it. It is important for us to progress in the Conditional Distributions work....

2025-02-14 20:26 UTC, adutfoy approved these changes
It is ok for me for the documentation! :-)

2025-02-14 20:28 UTC, adutfoy approved these changes

2025-02-15 07:57 UTC, jschueller commented
seems all my remarks have not been taken into account yet (unfold hidden items to see them)

2025-02-15 17:11 UTC, l-brevault commented on python/doc/examples/calibration/bayesian_calibration/plot_imh_python_distribution.py
> +
Yes ok perfect.

2025-02-15 17:12 UTC, l-brevault approved these changes
Thank you for all the modifications and for this very interesting work

2025-02-17 13:19 UTC, regislebrun commented on python/src/PosteriorDistribution.i
> -%ignore OT::PosteriorDistribution::computeLogLikelihood;
I confirm that these methods are of interest for the user!

2025-02-17 14:01 UTC, regislebrun commented
> not yet: seems all my remarks have not been taken into account yet (unfold hidden items to see them)

@jschueller could you point out one of the points you asked that I missed? I checked everything one more time and it looks ok to me!

2025-02-17 14:17 UTC, jschueller commented
click on the "load more" link after the "84 hidden items" you should see comments marked "Pending" in orange color about the swig macro etc

2025-02-17 15:46 UTC, regislebrun commented
> click on the "load more" link after the "84 hidden items" you should see comments marked "Pending" in orange color about the swig macro etc dont forget to rebase after Anne's changes in master

@jschueller I don't see anything like this... gitk tells me that I am in sync with remotes/origin/fix_posterior, and this one is based on master--remotes/origin/master.

2025-02-17 15:55 UTC, jschueller commented
![regis1](https://github.com/user-attachments/assets/37622312-c2fd-4177-bf1e-68d1b37b126c)

![regis2](https://github.com/user-attachments/assets/235745ba-fc7e-4a98-b55a-68c956c4050b)

2025-02-18 07:39 UTC, jschueller approved these changes

2025-02-18 07:39 UTC, merged