SmolyakExperiment: add stratification
openturns/openturns pull request #2843
Opened 2024-12-04 15:55 UTC by jschueller

- 1. Add FejerExperiment class to expose nodes&weight from FejerAlgorithm as a DOE
- 2. Add WeightedExperiment.setLevel service, used in FejerExperiment to use size=2^L-1 nodes (default=NotYetImplemented for non-stratified DOEs)
- 3. In SmolyakExperiment, use setLevel if possible instead of setSize, thus allowing for stratified tensorization

To discuss:
- Should we drop FejerAlgorithm and use FejerExperiment+ExperimentIntegration ?
- Or only move FejerAlgorithm code to FejerExperiment so FejerAlgorithm uses FejerExperiment ?
- thoughts on WeightedExperiment.setLevel ? Add a boolean isStratified ? (note that we have a StratifiedExperiment in base, with stratification service setLevels)

Closes #2842

Do you have first thoughts @mbaudin47 ?

2024-12-10 09:17 UTC, mbaudin47 commented
Very well done: thank you for this feature. 

- "_Should we drop `FejerAlgorithm` and use `FejerExperiment`+`ExperimentIntegration` ?_" I don't think so. In #2709, I explain why the design of `ExperimentIntegration` could be improved since it does not inherits from `IntegrationAlgorithmImplementation` which can be seen here:

https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/WeightedExperiments/openturns/ExperimentIntegration.hxx#L34

  Instead, `FejerAlgorithm` currently inherits from `IntegrationAlgorithmImplementation`, as can be seen here:

https://github.com/openturns/openturns/blob/master/lib/src/Base/Algo/openturns/FejerAlgorithm.hxx#L35

  This is why removing `FejerAlgorithm` cannot be currently done, because it removes a feature that is not fullfilled by `ExperimentIntegration`.

- "_Or only move FejerAlgorithm code to FejerExperiment so FejerAlgorithm uses FejerExperiment ?_" This seems correct from my point of view.
- "_thoughts on WeightedExperiment.setLevel ? note that we have a StratifiedExperiment in base, with stratification service setLevels."_ I have to make a full review of the PR before I can have a view on this.

2024-12-12 15:28 UTC, jschueller commented on lib/src/Uncertainty/Algorithm/WeightedExperiments/WeightedExperimentImplementation.cxx
> +  throw NotYetImplementedException(HERE) << getClassName() << " does not support nesting levels";
= setSize(product(levels))

2024-12-12 15:30 UTC, jschueller commented on lib/src/Uncertainty/Algorithm/WeightedExperiments/FejerExperiment.cxx
> +    discretization[i] = SpecFunc::IPow(2.0, levels[i]) - 1;
add a flag to decide whether to interpret the levels as levels or sizes

2025-01-16 09:57 UTC, mbaudin47 commented on lib/src/Uncertainty/Algorithm/WeightedExperiments/FejerExperiment.cxx
> +  throw NotDefinedException(HERE) << "in FejerExperiment::setSize";
With `setUseNestedLevels(False)`, this is not a limitation anymore: we can use un-nested Fejer experiment.

2025-02-06 16:19 UTC, mbaudin47 approved these changes

2025-02-12 10:13 UTC, adutfoy commented
Thanks for this new development.
I suggest some points: 

1. we should precise that the way all the nodes and weights are computed  is documented on the class FejerAlgorithm. 
2. we should add the link to https://en.wikipedia.org/wiki/Clenshaw%E2%80%93Curtis_quadrature which is very usefull (english version).

It is ok for me to merge it in the library.

2025-02-12 10:20 UTC, adutfoy requested changes
Thanks for this new development.
I suggest some points: 

1. we should precise that the way all the nodes and weights are computed  is documented on the class FejerAlgorithm. 
2. we should add the link to https://en.wikipedia.org/wiki/Clenshaw%E2%80%93Curtis_quadrature which is very usefull (english version).

It is ok for me to merge it in the library.

2025-02-12 10:35 UTC, jschueller commented
agreed, I moved the nodes/weights expression to fejerexperiment and referenced it from fejeralgorithm

2025-02-12 12:48 UTC, merged